---
permalink: task-deploy-bluexp-backup-and-recovery-for-vms.html 
sidebar: sidebar 
keywords: deploy, bluexp, backup, recovery for VMs 
summary: Per proteggere macchine virtuali, datastore e database coerenti con le applicazioni su macchine virtualizzate, è necessario implementare il backup e ripristino BlueXP per le macchine virtuali. 
---
= Implementazione del backup e ripristino BlueXP per le macchine virtuali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per proteggere macchine virtuali, datastore e database coerenti con le applicazioni su macchine virtualizzate, è necessario implementare il backup e ripristino BlueXP per le macchine virtuali.

.Prima di iniziare
++ ++

[NOTE]
====
L'implementazione di OVA è supportata in VMware vCenter 8.0 e versioni successive.

====
* È necessario aver letto i requisiti di implementazione.
* È necessario eseguire una versione supportata di VMC su AWS.
* È necessario aver configurato e configurato il VMC sull'ambiente AWS.
* È necessario aver configurato un host ESXi per il backup e ripristino BlueXP per le macchine virtuali.
* È necessario aver scaricato il backup e ripristino BlueXP per le macchine virtuali `.tar` file.
* È necessario disporre dei dettagli di autenticazione di accesso per l'istanza di VMC su AWS.
* È necessario disporre di un certificato con file di chiavi pubbliche e private validi. Per ulteriori informazioni, consulta gli articoli della sezione Storage Certificate Management.
* È necessario disconnettersi e chiudere tutte le sessioni del browser del client vSphere ed eliminare la cache del browser per evitare qualsiasi problema di cache del browser durante l'implementazione del backup e ripristino BlueXP per le macchine virtuali.
* È necessario aver attivato TLS (Transport Layer Security) in vCenter. Consultare la documentazione VMware.


Implementazione del backup e ripristino BlueXP per le macchine virtuali nello stesso fuso orario di vCenter.

.Fasi
. Per VMware vCenter 7.0.3 e versioni successive, seguire la procedura descritta nella sezione Download di Open Virtual Appliance (OVA) per importare i certificati in vCenter.
. Nel browser, accedere a VMware vSphere vCenter.
. Accedere alla pagina *VMware vCenter Single Sign-on*.
. Nel riquadro Navigator, fare clic con il pulsante destro del mouse su qualsiasi oggetto di inventario che sia un oggetto padre valido di una macchina virtuale, ad esempio un data center, un cluster o un host, quindi selezionare *Deploy OVF Template* (implementa modello OVF) per avviare la procedura guidata di implementazione di VMware.
. Estrarre il `.tar` che contiene `.ova` sul sistema locale. Nella pagina *Select an OVF template* (Seleziona un modello OVF), specificare la posizione di `.ova` file all'interno di `.tar` cartella estratta.
. Fare clic su *Avanti*.
. Nella pagina *Select a name and folder* (Seleziona un nome e una cartella), immettere un nome univoco per la macchina virtuale o la vApp, selezionare un percorso di implementazione, quindi fare clic su *Next* (Avanti).
+
Questa operazione specifica dove importare `.ova` File in vCenter. Il nome predefinito per la macchina virtuale è lo stesso del nome della macchina selezionata `.ova` file. Se si modifica il nome predefinito, scegliere un nome univoco all'interno di ciascuna cartella VMC su AWS VM.

+
La posizione di implementazione predefinita per la macchina virtuale è l'oggetto di inventario in cui è stata avviata la procedura guidata.

. Nella pagina *Select a resource* (Seleziona una risorsa), selezionare la risorsa in cui si desidera eseguire il modello di macchina virtuale distribuito e fare clic su *Next* (Avanti).
. Nella pagina *Dettagli revisione*, verificare `.ova` Dettagli del modello e fare clic su *Avanti*.
. Nella pagina *contratti di licenza*, selezionare la casella di controllo *Accetto tutti i contratti di licenza*.
. Nella pagina *Select storage*, definire dove e come memorizzare i file per il modello OVF distribuito.
+
.. Selezionare il formato del disco per i VMDK.
.. Selezionare un criterio di storage della macchina virtuale.
+
Questa opzione è disponibile solo se i criteri di storage sono attivati sulla risorsa di destinazione.

.. Selezionare un datastore per memorizzare il modello OVA implementato.
+
Il file di configurazione e i file dei dischi virtuali vengono memorizzati nell'archivio dati.

+
Selezionare un datastore di dimensioni tali da ospitare la macchina virtuale o la vApp e tutti i file dei dischi virtuali associati.



. Nella pagina *Select networks* (Seleziona reti), effettuare le seguenti operazioni:
+
.. Selezionare una rete di origine e associarla a una rete di destinazione.
+
La colonna Source Network (rete di origine) elenca tutte le reti definite nel modello OVA.

.. Nella sezione *IP Allocation Settings* (Impostazioni allocazione IP), selezionare il protocollo IP richiesto e fare clic su *Next* (Avanti).
+
Il backup e ripristino BlueXP per le macchine virtuali supporta un'unica interfaccia di rete. Se sono necessari più adattatori di rete, è necessario impostarli manualmente.



. Nella pagina *Personalizza modello*, effettuare le seguenti operazioni:
+
.. Nella sezione *Register to existing vCenter* (Registra su vCenter esistente), immettere il nome vCenter e le credenziali vCenter dell'appliance virtuale.
+
Nel campo *vCenter username*, inserire il nome utente nel formato dominio/nomeutente.

.. Nella sezione *Crea backup e ripristino BlueXP per le credenziali delle macchine virtuali*, immettere le credenziali locali.
+
Nel campo *Nome utente*, immettere il nome utente locale; non includere i dettagli del dominio.

+
[IMPORTANT]
====
Annotare il nome utente e la password specificati. È necessario utilizzare queste credenziali se si desidera modificare il backup e il ripristino BlueXP per la configurazione delle macchine virtuali in un secondo momento.

====
.. Immettere le credenziali per l'utente principale.
.. In *Setup Network Properties* (Impostazioni proprietà di rete), immettere il nome host.
+
... Nella sezione *Setup IPv4 Network Properties* (impostazione delle proprietà di rete IPv4), immettere le informazioni di rete, ad esempio indirizzo IPv4, Netmask IPv4, gateway IPv4, DNS primario IPv4, DNS secondario IPv4, E IPv4 Search Domains.
+
[IMPORTANT]
====
Se si desidera procedere con DHCP come configurazione di rete, è possibile saltare questi passaggi e lasciare vuote le voci nella sezione Setup Network Properties (impostazione delle proprietà di rete).

====


.. In *Setup Date and Time* (Data e ora di installazione), selezionare il fuso orario in cui si trova vCenter.


. Nella pagina *Pronto per il completamento*, esaminare la pagina e fare clic su *fine*.
+
Tutti gli host devono essere configurati con indirizzi IP (i nomi host FQDN non sono supportati). L'operazione di implementazione non convalida l'input prima dell'implementazione.

+
È possibile visualizzare lo stato di avanzamento della distribuzione dalla finestra Recent Tasks (attività recenti) mentre si attende il completamento delle attività di importazione e distribuzione di OVF.

+
Quando il backup e ripristino BlueXP per le macchine virtuali viene implementato correttamente, viene implementato come macchina virtuale Linux, registrata con vCenter, e viene installato un client VMware vSphere.

. Accedere alla macchina virtuale in cui è stato implementato il backup e ripristino BlueXP per le macchine virtuali, quindi fare clic sulla scheda *Riepilogo*, quindi fare clic sulla casella *accensione* per avviare l'appliance virtuale.
. Mentre il backup e ripristino BlueXP per le macchine virtuali è in fase di accensione, fare clic con il pulsante destro del mouse sul backup e ripristino BlueXP implementati per le macchine virtuali, selezionare *sistema operativo guest*, quindi fare clic su *Installa strumenti VMware*.

