---
permalink: task-download-the-open-virtual-appliance.html 
sidebar: sidebar 
keywords: download, open virtual appliance 
summary: 'Scarica Open Virtual Appliance (OVA) in VMware vCenter 8,0 e versioni successive per implementare il backup e il ripristino BlueXP per le VM.' 
---
= Scaricare Open Virtual Appliance
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scarica Open Virtual Appliance (OVA) in VMware vCenter 8,0 e versioni successive per implementare il backup e il ripristino BlueXP per le VM.

.Prima di iniziare
Se l'OVA firmato dal certificato Entrust non è attendibile, assicurarsi di installare e aggiungere certificati intermedi a vCenter.

.Fasi
. Per scaricare il backup e ripristino BlueXP per le macchine virtuali OVA:
+
.. Accedere a. https://mysupport.netapp.com/products/index.html["Sito di supporto NetApp"^]
.. Dall'elenco dei prodotti, selezionare *BlueXP backup and recovery for vms*, quindi fare clic sul pulsante *Download Latest Release* (Scarica ultima release).
.. Scarica il backup e ripristino BlueXP per le macchine virtuali `.tar` file in qualsiasi posizione.


. Estrarre il contenuto del file tar. Il file tar contiene la cartella OVA e certs. La cartella certs contiene certificati intermedi.
. Nel client vSphere, accedere a *Administration > Certificates > Certificate Management*.
. Accanto a *certificati root attendibili*, fare clic su *Aggiungi*.
+

NOTE: Per impostazione predefinita, viene installato il certificato di origine.

+
.. Accedere alla cartella Cercs.
.. Selezionare i certificati intermedi.
.. Installare ciascun certificato uno alla volta.


. I certificati vengono aggiunti a un pannello in certificati root attendibili.
+
Una volta installati i certificati, è possibile verificare e implementare OVA.



[NOTE]
====
Se l'OVA scaricato non viene manomesso, nella colonna Publisher viene visualizzato certificato attendibile.

====