---
permalink: whats-new.html 
sidebar: sidebar 
keywords: 2-node switched Cisco 92300YC cluster switch migration 
summary: Scopri le novità di BlueXP backup e recovery per macchine virtuali. 
---
= Novità del backup e ripristino BlueXP per le macchine virtuali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri le novità del backup e ripristino BlueXP per le macchine virtuali.



== 18 gennaio 2024



=== Miglioramenti al backup e recovery di BlueXP per le VM

Di seguito sono elencate le funzionalità supportate nel backup e ripristino BlueXP per le VM 1,1:

* Montare e smontare gli archivi dati
* Collegare e scollegare i VMDK
* Ripristinare le macchine virtuali in una posizione alternativa
* Attiva il blocco delle Snapshot per garantire che le copie Snapshot non vengano manomesse fino a un momento specificato.




== 13 luglio 2023



=== Il backup e ripristino BlueXP per le macchine virtuali 1.0 è ora GA

È possibile proteggere i dati sulle macchine virtuali utilizzando il backup e ripristino BlueXP per le macchine virtuali. Puoi eseguire il backup dei datastore su Amazon FSX e ripristinare le macchine virtuali nella posizione originale.

Questa soluzione è specifica per macchine virtuali e datastore su VMware Cloud su AWS e Amazon FSX per NetApp ONTAP.

link:concept-bluexp-backup-and-recovery-for-virtual-machines-on-amazon-fsx.html["Backup e ripristino BlueXP per macchine virtuali su Amazon FSX"]
